### PR TITLE
Fix Exact is always true

### LINKED ISSUE #81: Bug: EXACT() returns always true in v2.9.2
Hello, I noticed that in the latest versions executing EXACT formula returns true even though the arguments are not equal.

[Here](https://stackblitz.com/edit/angular-ivy-no7muq?devtoolsheight=33&file=src/app/app.component.ts) is a stackblitz demonstrating it

`console.log(FORMULA.EXACT('Word', '0'));` logs true

The latest working version I tried is the one deployed in https://formulajs.info/functions/, which seems to be 2.6.9

Thank you!

image

### PR DESCRIPTION
**Pull request by manuphatak**
## Summary

fixes #81

`utils.toString` is converting nearly everything to `[Object object]` -- even undefined and null.  

`utils.parseString` seems like the more appropriate utility:

https://github.com/formulajs/formulajs/blob/5c033102658d86f34cee89b6edd77959c225651d/lib/utils/common.js#L122-L131

### CODE REVIEW

File: lib/text.js [hunk 1]
```diff
@@ -79,12 +79,12 @@ exports.EXACT = function(text1, text2) {
   if (arguments.length !== 2) {
     return error.na;
   }
-  var someError = utils.anyError(text1, text1);
+  var someError = utils.anyError(text1, text2);
```
Comment (manuphatak) [inline lib/text.js:82]: I believe `utils.anyError(text1, text1)` is a typo.

Looking at `util.anyError` it doesn't look like you would want to pass it the same argument twice: 

https://github.com/formulajs/formulajs/blob/5c033102658d86f34cee89b6edd77959c225651d/lib/utils/common.js#L238-L245

Comment (nicolashefti) [reply lib/text.js:82]: Agreed

File: lib/text.js [hunk 2]
```diff
@@ -79,12 +79,12 @@ exports.EXACT = function(text1, text2) {
...
   if (someError) {
     return someError;
   }
-  text1 = utils.toString(text1);
-  text2 = utils.toString(text2);
+  text1 = utils.parseString(text1);
```
Comment (nicolashefti) [inline lib/text.js:86]: I think this was a typo too. The function toString() does not exist in the common module. That's why you get the toString() of any Object in JS: "[object Object]"

**Review by nicolashefti — APPROVED** [review]
Thanks for your contribution!
